#!/usr/bin/env bash
#
# Builds pandabot.zip, optionally baking per-site values into the plugin.
#
#   ./build.sh                          # generic zip, no site values
#   ./build.sh pandabot.config.json     # zip with your values baked in
#
# With no argument it uses pandabot.config.json if that file exists, so the
# usual case is just ./build.sh. Values come from a gitignored config file so
# the repository itself never carries one clinic's phone number.
#
# The plugin source is never modified: the build runs against a throwaway copy
# in a temp directory. A wrong config can only produce a bad zip, never a
# dirty working tree.

set -euo pipefail

cd "$(dirname "$0")"

PLUGIN_DIR="pandabot"
OUT_ZIP="pandabot.zip"
CONFIG="${1:-pandabot.config.json}"

command -v python3 >/dev/null || { echo "build.sh needs python3" >&2; exit 1; }
command -v zip     >/dev/null || { echo "build.sh needs zip" >&2; exit 1; }
[ -d "$PLUGIN_DIR" ] || { echo "no $PLUGIN_DIR/ directory here" >&2; exit 1; }

BUILD_ROOT="$(mktemp -d)"
trap 'rm -rf "$BUILD_ROOT"' EXIT

cp -R "$PLUGIN_DIR" "$BUILD_ROOT/$PLUGIN_DIR"
# Never ship a stale site-config.php that happened to be lying around.
rm -f "$BUILD_ROOT/$PLUGIN_DIR/site-config.php"

if [ -f "$CONFIG" ]; then
	echo "Using config: $CONFIG"
	python3 - "$CONFIG" "$BUILD_ROOT/$PLUGIN_DIR/site-config.php" <<'PY'
import json, sys, datetime

config_path, out_path = sys.argv[1], sys.argv[2]

with open(config_path, encoding='utf-8') as fh:
    cfg = json.load(fh)

# config key -> PHP constant. Mirrors Pandabot_Settings::constant_map().
MAPPING = {
    ('contact', 'booking_url'):          'PANDABOT_CONTACT_BOOKING_URL',
    ('contact', 'phone'):                'PANDABOT_CONTACT_PHONE',
    ('contact', 'whatsapp'):             'PANDABOT_CONTACT_WHATSAPP',
    ('contact', 'email'):                'PANDABOT_CONTACT_EMAIL',
    ('contact', 'address'):              'PANDABOT_CONTACT_ADDRESS',
    ('contact', 'privacy_url'):          'PANDABOT_CONTACT_PRIVACY_URL',
    ('providers', 'chat_base_url'):       'PANDABOT_CHAT_BASE_URL',
    ('providers', 'chat_model'):          'PANDABOT_CHAT_MODEL',
    ('providers', 'chat_api_key'):        'PANDABOT_CHAT_API_KEY',
    ('providers', 'embeddings_base_url'): 'PANDABOT_EMBEDDINGS_BASE_URL',
    ('providers', 'embeddings_model'):    'PANDABOT_EMBEDDINGS_MODEL',
    ('providers', 'embeddings_api_key'):  'PANDABOT_EMBEDDINGS_API_KEY',
}

SECRET = {'PANDABOT_CHAT_API_KEY', 'PANDABOT_EMBEDDINGS_API_KEY'}

lines, baked, secrets = [], [], []
for (section, key), constant in MAPPING.items():
    value = cfg.get(section, {}).get(key, '')
    if not isinstance(value, str) or value.strip() == '':
        continue
    value = value.strip()
    if constant in SECRET:
        secrets.append(constant)
    # single-quoted PHP: only \ and ' are special
    escaped = value.replace('\\', '\\\\').replace("'", "\\'")
    lines.append(f"define( '{constant}', '{escaped}' );")
    baked.append(constant)

if not lines:
    print("  no values set — building a generic zip")
    sys.exit(0)

header = f"""<?php
/**
 * Generated by build.sh on {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')} — do not edit by hand.
 * Regenerate by editing your config file and re-running ./build.sh.
 *
 * These constants override the matching settings at read time. The settings
 * screen shows each of them as locked, and they are never written into the
 * database.
 */

if ( ! defined( 'ABSPATH' ) ) {{
\texit;
}}

"""

with open(out_path, 'w', encoding='utf-8') as fh:
    fh.write(header + '\n'.join(lines) + '\n')

print(f"  baked in {len(baked)} value(s): {', '.join(sorted(baked))}")

if secrets:
    print()
    print("  !! WARNING: an API key is baked into this zip:")
    for s in secrets:
        print(f"       {s}")
    print("     The key is now in a PHP file inside the zip and inside your")
    print("     web root. Do not share this zip. Prefer wp-config.php")
    print("     constants or the admin screen instead.")
    print()
PY
else
	echo "No config file at $CONFIG — building a generic zip."
	echo "(Copy pandabot.config.example.json to pandabot.config.json to bake in your values.)"
fi

rm -f "$OUT_ZIP"
( cd "$BUILD_ROOT" && zip -rq "$OLDPWD/$OUT_ZIP" "$PLUGIN_DIR" -x "*.DS_Store" )

VERSION="$(grep -oP "define\( 'PANDABOT_VERSION', '\K[^']+" "$PLUGIN_DIR/pandabot.php")"
echo "Built $OUT_ZIP (v$VERSION, $(unzip -l "$OUT_ZIP" | tail -1 | awk '{print $2}') files)"
